version: "2"
services:
  ## Defines the configuration for the database service.
  db:
    container_name: studentdb_container_next
    image: mysql:5.7
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: studentdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  ## Defines the configuration for the python application service.
  app:
    build: ./app
    links:
      - db
    ports:
      - "5001:5000"
    depends_on:
      - db
      
  ## Defines the configuration for the nextjs application service.
  next-app:
    build: ./next-app
    links:
      - app
    ports:
      - "3000:3000"
    depends_on:
      - app
      