version: "2"
services:  
  ## Defines the configuration for the database service.
  db:          
    container_name: studentdb_container
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: studentdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

  ## Defines the configuration for the python application service.
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
      