version: "2"

# Defines the services to be created and managed by Docker Compose.
services:
    ## Defines the configuration for the database service.
    mysql-development:
        container_name: employeedb_container
        image: mysql:8.0.17
        ports:
          - "3307:3306"
        environment:
          MYSQL_ROOT_PASSWORD: root_pass
          MYSQL_DATABASE: employeedb
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
